name: "Build&Deploy ros-tools images"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  # on:
  #   release:
  #     types: [released]
jobs:
  ros-tools-melodic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: melodic/Dockerfile
      docker_image: registry.cloud.mov.ai/devops/ros-tools-melodic
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
  ros-tools-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: noetic/Dockerfile
      docker_image: registry.cloud.mov.ai/devops/ros-tools-noetic
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
